// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Hashtbl = require("bs-platform/lib/js/hashtbl.js");

var values = Hashtbl.create(/* None */0, 30);

Hashtbl.add(values, "0-1", 2);

Hashtbl.add(values, "0-3", 6);

Hashtbl.add(values, "0-5", 8);

Hashtbl.add(values, "1-0", 5);

Hashtbl.add(values, "1-1", 8);

Hashtbl.add(values, "1-5", 9);

Hashtbl.add(values, "1-6", 7);

Hashtbl.add(values, "2-4", 4);

Hashtbl.add(values, "3-0", 3);

Hashtbl.add(values, "3-1", 7);

Hashtbl.add(values, "3-6", 5);

Hashtbl.add(values, "4-0", 6);

Hashtbl.add(values, "4-8", 4);

Hashtbl.add(values, "5-2", 8);

Hashtbl.add(values, "5-7", 1);

Hashtbl.add(values, "5-8", 3);

Hashtbl.add(values, "6-4", 2);

Hashtbl.add(values, "7-2", 9);

Hashtbl.add(values, "7-3", 8);

Hashtbl.add(values, "7-7", 3);

Hashtbl.add(values, "7-8", 6);

Hashtbl.add(values, "8-3", 3);

Hashtbl.add(values, "8-5", 6);

Hashtbl.add(values, "8-7", 9);

var one = values;

exports.one = one;
/* values Not a pure module */
