// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReactDOMRe  = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("BoardHeading");

var color = "#0055CC";

var style = {
  color: color,
  fontFamily: "'Rubik', sans-serif",
  fontSize: "48px",
  fontWeight: "900",
  margin: "0"
};

var smallStyle = ReactDOMRe.Style[/* combine */0](style, {
      fontWeight: "400"
    });

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("h1", {
                  style: style
                }, "Sudoku", React.createElement("small", {
                      style: smallStyle
                    }, "ReasonML"));
    });
  return newrecord;
}

exports.component  = component;
exports.color      = color;
exports.style      = style;
exports.smallStyle = smallStyle;
exports.make       = make;
/* component Not a pure module */
