// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("BoardFooter");

var color = "#0055CC";

var style = {
  color: color,
  fontFamily: "'Rubik', sans-serif",
  fontSize: "16px",
  fontWeight: "400",
  margin: "8px 0",
  textAlign: "center"
};

var linkStyle = {
  color: color
};

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: style
                }, "Created by ", React.createElement("a", {
                      style: linkStyle,
                      href: "https://github.com/skovy",
                      target: "_blank"
                    }, "Skovy"), " on ", React.createElement("a", {
                      style: linkStyle,
                      href: "https://github.com/skovy/sudoku-reasonml",
                      target: "_blank"
                    }, "GitHub"), ".");
    });
  return newrecord;
}

exports.component = component;
exports.color     = color;
exports.style     = style;
exports.linkStyle = linkStyle;
exports.make      = make;
/* component Not a pure module */
