// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe         = require("reason-react/src/ReactDOMRe.js");
var ReasonReact        = require("reason-react/src/ReasonReact.js");
var Page$ReactTemplate = require("./Page.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Page$ReactTemplate.make(/* array */[])), "index");

/*  Not a pure module */
