// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array    = require("bs-platform/lib/js/array.js");
var Hashtbl    = require("bs-platform/lib/js/hashtbl.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var values = Hashtbl.create(/* None */0, 10);

Hashtbl.add(values, "0-0", 3);

Hashtbl.add(values, "0-6", 5);

Hashtbl.add(values, "1-0", 7);

Hashtbl.add(values, "1-1", 8);

Hashtbl.add(values, "1-2", 9);

Hashtbl.add(values, "1-4", 1);

Hashtbl.add(values, "1-5", 5);

Hashtbl.add(values, "1-8", 2);

Hashtbl.add(values, "2-1", 1);

Hashtbl.add(values, "2-6", 8);

Hashtbl.add(values, "2-8", 6);

function generateInitialBoard(providedValues) {
  var board = /* array */[];
  for(var i = 0; i <= 8; ++i){
    var row = /* int array */[];
    for(var j = 0; j <= 8; ++j){
      var key = Pervasives.string_of_int(i) + ("-" + Pervasives.string_of_int(j));
      row = Hashtbl.mem(providedValues, key) ? $$Array.append(row, /* int array */[Hashtbl.find(providedValues, key)]) : $$Array.append(row, /* int array */[0]);
    }
    board = $$Array.append(board, /* array */[row]);
  }
  return board;
}

var one = values;

exports.one                  = one;
exports.generateInitialBoard = generateInitialBoard;
/* values Not a pure module */
