// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array           = require("bs-platform/lib/js/array.js");
var React             = require("react");
var Hashtbl           = require("bs-platform/lib/js/hashtbl.js");
var Pervasives        = require("bs-platform/lib/js/pervasives.js");
var ReasonReact       = require("reason-react/src/ReasonReact.js");
var Box$ReactTemplate = require("./Box.bs.js");

var component = ReasonReact.statelessComponent("Row");

var style = {
  display: "flex",
  alignItems: "center",
  justifyContent: "flex-start"
};

function make(handleChange, index, row, startingBoard, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "row",
                  style: style
                }, $$Array.mapi((function (j, column) {
                        return ReasonReact.element(/* Some */[Pervasives.string_of_int(j)], /* None */0, Box$ReactTemplate.make(column, /* Some */[Hashtbl.mem(startingBoard, Pervasives.string_of_int(index) + ("-" + Pervasives.string_of_int(j)))], handleChange, index, j, /* array */[]));
                      }), row));
    });
  return newrecord;
}

exports.component = component;
exports.style     = style;
exports.make      = make;
/* component Not a pure module */
